generated_at:
  commit: 3322511885371d2b2253f209ccc3aa60d4100cfd
  apis:
    - path: google/apps/script/type
    - path: google/apps/script/type/gmail
    - path: google/apps/script/type/docs
    - path: google/apps/script/type/drive
    - path: google/apps/script/type/sheets
    - path: google/apps/script/type/calendar
    - path: google/apps/script/type/slides
release:
  published:
    version: 0.4.0
    commit: 3322511885371d2b2253f209ccc3aa60d4100cfd