// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"strings"

	"github.com/julieqiu/exp/surfer/internal/sidekick/api"
	"github.com/julieqiu/exp/surfer/internal/gcloudyaml"
)

// GenerateCommand generates a gcloud command from an API method.
func GenerateCommand(method *api.Method, apiCfg *gcloudyaml.API, track gcloudyaml.ReleaseTrack) *Command {
	cmdName := DeriveCommandName(method.Name)
	resourceName := strings.TrimSuffix(apiCfg.Name, "Service")

	return &Command{
		ReleaseTracks: []gcloudyaml.ReleaseTrack{track},
		Autogenerated: true,
		Hidden:        apiCfg.RootIsHidden,
		HelpText: &CommandHelpText{
			Brief:       fmt.Sprintf("%s %s", strings.Title(cmdName), resourceName),
			Description: fmt.Sprintf("%s a %s resource.", strings.Title(cmdName), resourceName),
			Examples:    fmt.Sprintf("To %s a resource, run:\n\n$ {command}", cmdName),
		},
		Arguments: generateArguments(method),
		Request: &Request{
			APIVersion: apiCfg.APIVersion,
			Collection: []string{fmt.Sprintf("%s.projects.locations.%s", strings.ToLower(resourceName), strings.ToLower(resourceName))},
			Method:     method.Name,
		},
	}
}

func generateArguments(method *api.Method) *Arguments {
	params := []*Param{}
	if method.InputType != nil {
		for _, field := range method.InputType.Fields {
			// Skip parent and name fields for now, as they are often handled specially.
			if field.Name == "parent" || field.Name == "name" {
				continue
			}
			params = append(params, &Param{
				ArgName:  field.JSONName,
				APIField: field.Name,
				HelpText: field.Documentation,
				Required: !field.Optional,
			})
		}
	}

	// Add a positional argument for the resource name for non-list commands.
	cmdName := DeriveCommandName(method.Name)
	if cmdName != "list" {
		resourceName := "resource"
		if method.InputType != nil && len(method.InputType.Fields) > 0 {
			resourceName = strings.ToLower(strings.TrimSuffix(method.InputType.Fields[0].Parent.Name, "Request"))
		}
		params = append(params, &Param{
			ArgName:      "name",
			HelpText:     fmt.Sprintf("The name of the %s resource.", resourceName),
			IsPositional: true,
			Required:     true,
		})
	}

	return &Arguments{
		Params: params,
	}
}