generated_at:
  commit: 3322511885371d2b2253f209ccc3aa60d4100cfd
  apis:
    - path: google/analytics/data/v1alpha
    - path: google/analytics/data/v1beta
release:
  published:
    version: 0.19.0
    commit: 3322511885371d2b2253f209ccc3aa60d4100cfd