generated_at:
  commit: e8365a7f88fabe8717cb8322b8ce784b03b6daea
  apis:
    - path: google/ads/admanager/v1
release:
  published:
    version: 0.6.0
    commit: e8365a7f88fabe8717cb8322b8ce784b03b6daea