generated_at:
  commit: 3322511885371d2b2253f209ccc3aa60d4100cfd
  apis:
    - path: google/apps/events/subscriptions/v1
    - path: google/apps/events/subscriptions/v1beta
release:
  published:
    version: 0.3.0
    commit: 3322511885371d2b2253f209ccc3aa60d4100cfd